
// This file was generated by Prisma and assumes you have installed the following:
// npm install --save-dev prisma dotenv
const envFile = process.env.NODE_ENV === 'test' ? '.env.test' : '.env';
require('dotenv').config({ path: envFile });

import { defineConfig, env } from "prisma/config";

export default defineConfig({
	schema: "prisma/schema.prisma",
	migrations: {
		path: "prisma/migrations",
		seed: 'tsx prisma/seed.ts',
	},
	// engine: "classic",
	datasource: {
		url: env("DATABASE_URL"),
	},
});
